DROP TABLE ANALYTICS_CERTIFICATION_FACT;

DROP TABLE ANALYTICS_PROVISIONING_CREATED_ENTRY_FACT;

DROP TABLE ANALYTICS_PROVISIONING_DETAIL_FACT;

DROP TABLE ANALYTICS_PROVISIONING_FACT;

DROP TABLE ANALYTICS_PROVISIONING_FINISHED_ENTRY_FACT;

DROP TABLE ANALYTICS_PROVISIONING_TASK_FACT;

DROP TABLE ANALYTICS_RECONCILIATION_FACT;

DROP TABLE ANALYTICS_RECONCILIATION_SITUATION_DIMENSION;

DROP TABLE ANALYTICS_RECONCILIATION_SITUATION_FACT;

DROP TABLE ANALYTICS_REQUEST_APPROVAL_TASK_DETAIL_FACT;

DROP TABLE ANALYTICS_REQUEST_AVERAGE_FACT;

DROP TABLE ANALYTICS_REQUEST_DETAIL_CREATED_GENERAL_FACT;

DROP TABLE ANALYTICS_REQUEST_DETAIL_CREATED_MANUAL_FACT;

DROP TABLE ANALYTICS_REQUEST_DETAIL_CREATED_SYSTEM_FACT;

DROP TABLE ANALYTICS_REQUEST_DETAIL_FACT;

DROP TABLE ANALYTICS_REQUEST_DETAIL_FINALIZED_GENERAL_FACT;

DROP TABLE ANALYTICS_REQUEST_DETAIL_FINALIZED_MANUAL_FACT;

DROP TABLE ANALYTICS_REQUEST_DETAIL_FINALIZED_SYSTEM_FACT;

DROP TABLE ANALYTICS_REQUEST_FACT;

DROP TABLE ANALYTICS_REQUEST_FASTEST_APPROVERS;

DROP TABLE ANALYTICS_REQUEST_HIGH_AMOUNT_APPROVERS;

DROP TABLE ANALYTICS_REQUEST_LESS_AMOUNT_APPROVERS;

DROP TABLE ANALYTICS_REQUEST_SLOWEST_APPROVERS;

DROP TABLE ANALYTICS_TASK_DAILY_FACT;

DROP TABLE ANALYTICS_TASK_DEADLINE_FACT;

DROP TABLE ANALYTICS_TASK_FACT;

DROP TABLE ANALYTICS_TASK_QUEUE_FACT;


