
-- 18-09-2019

ALTER TABLE ANALYTICS_REQUEST_DETAIL_FACT ADD COLUMN amountByWaitingApprovalStatus bigint;


ALTER TABLE ANALYTICS_REQUEST_DETAIL_FACT ADD COLUMN amountByLockUserType bigint;

ALTER TABLE ANALYTICS_REQUEST_DETAIL_FACT ADD COLUMN amountByUnlockUserType bigint;

ALTER TABLE ANALYTICS_REQUEST_DETAIL_FACT ADD COLUMN amountByUpdateAccountType bigint;

ALTER TABLE ANALYTICS_REQUEST_DETAIL_FACT ADD COLUMN amountByActivateAccountType bigint;

ALTER TABLE ANALYTICS_REQUEST_DETAIL_FACT ADD COLUMN amountByInactivateAccountType bigint;

ALTER TABLE ANALYTICS_REQUEST_DETAIL_FACT ADD COLUMN amountByRemoveUserFromRoleType bigint;





