
-- amountTasks

ALTER TABLE ANALYTICS_CERTIFICATION_EXECUTOR_FACT
add amountTasks BIGINT;


-- amountOpenEntries

ALTER TABLE ANALYTICS_CERTIFICATION_CAMPAIGN_RESUME_FACT
    ADD COLUMN amountOpenEntries BIGINT;

alter table ANALYTICS_CERTIFICATION_MICRO_RESUME_FACT
   add amountOpenEntries BIGINT;

alter table ANALYTICS_CERTIFICATION_SELECTOR_RESUME_FACT
   add amountOpenEntries BIGINT;


-- amountOpenTasks

ALTER TABLE ANALYTICS_CERTIFICATION_CAMPAIGN_RESUME_FACT
    ADD COLUMN amountOpenTasks BIGINT;

ALTER TABLE ANALYTICS_CERTIFICATION_MICRO_RESUME_FACT
    ADD COLUMN amountOpenTasks BIGINT;

ALTER TABLE ANALYTICS_CERTIFICATION_SELECTOR_RESUME_FACT
    ADD COLUMN amountOpenTasks BIGINT;
