
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_CERTIFICATION_CAMPAIGN_DETAIL_FACT';
desc ANALYTICS_CERTIFICATION_CAMPAIGN_DETAIL_FACT ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_CERTIFICATION_CAMPAIGN_POLICY_DIMENSION';
desc ANALYTICS_CERTIFICATION_CAMPAIGN_POLICY_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_CERTIFICATION_CAMPAIGN_RESUME_FACT';
desc ANALYTICS_CERTIFICATION_CAMPAIGN_RESUME_FACT ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_CERTIFICATION_EXECUTOR_FACT';
desc ANALYTICS_CERTIFICATION_EXECUTOR_FACT ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_CERTIFICATION_EXECUTOR_INSTANCE_DIMENSION';
desc ANALYTICS_CERTIFICATION_EXECUTOR_INSTANCE_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_CERTIFICATION_EXECUTOR_USER_DIMENSION';
desc ANALYTICS_CERTIFICATION_EXECUTOR_USER_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_CERTIFICATION_MICRO_DETAIL_FACT';
desc ANALYTICS_CERTIFICATION_MICRO_DETAIL_FACT ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_CERTIFICATION_MICRO_RESUME_FACT';
desc ANALYTICS_CERTIFICATION_MICRO_RESUME_FACT ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_CERTIFICATION_SELECTOR_DETAIL_FACT';
desc ANALYTICS_CERTIFICATION_SELECTOR_DETAIL_FACT ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_CERTIFICATION_SELECTOR_RESUME_FACT';
desc ANALYTICS_CERTIFICATION_SELECTOR_RESUME_FACT ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_CERTIFICATION_SELECTOR_SELECTOR_DIMENSION';
desc ANALYTICS_CERTIFICATION_SELECTOR_SELECTOR_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_CERTIFICATION_SELECTOR_USER_DIMENSION';
desc ANALYTICS_CERTIFICATION_SELECTOR_USER_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_CERTIFICATION_TASK_FACT';
desc ANALYTICS_CERTIFICATION_TASK_FACT ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_CERTIFICATION_TASK_INSTANCE_DIMENSION';
desc ANALYTICS_CERTIFICATION_TASK_INSTANCE_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_DIRECTORY_MANAGEMENT_DETAIL_FACT';
desc ANALYTICS_DIRECTORY_MANAGEMENT_DETAIL_FACT ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_DIRECTORY_OBJECTS_CREATION_DETAIL_FACT';
desc ANALYTICS_DIRECTORY_OBJECTS_CREATION_DETAIL_FACT ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_DIRECTORY_OBJECTS_DETAIL_FACT';
desc ANALYTICS_DIRECTORY_OBJECTS_DETAIL_FACT ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_DIRECTORY_OBJECTS_FACT';
desc ANALYTICS_DIRECTORY_OBJECTS_FACT ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_DIRECTORY_RISK_DETAIL_FACT';
desc ANALYTICS_DIRECTORY_RISK_DETAIL_FACT ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_PROVISIONING_ENTRY_ENTRY_DIMENSION';
desc ANALYTICS_PROVISIONING_ENTRY_ENTRY_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_PROVISIONING_ENTRY_FACT';
desc ANALYTICS_PROVISIONING_ENTRY_FACT ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_PROVISIONING_ENTRY_OPERATION_DIMENSION';
desc ANALYTICS_PROVISIONING_ENTRY_OPERATION_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_PROVISIONING_ENTRY_TYPE_DIMENSION';
desc ANALYTICS_PROVISIONING_ENTRY_TYPE_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_PROVISIONING_TASK_ENTRY_DIMENSION';
desc ANALYTICS_PROVISIONING_TASK_ENTRY_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_PROVISIONING_TASK_EXECUTOR_ENTRY_DIMENSION';
desc ANALYTICS_PROVISIONING_TASK_EXECUTOR_ENTRY_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_PROVISIONING_TASK_EXECUTOR_FACT';
desc ANALYTICS_PROVISIONING_TASK_EXECUTOR_FACT ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_PROVISIONING_TASK_EXECUTOR_TYPE_DIMENSION';
desc ANALYTICS_PROVISIONING_TASK_EXECUTOR_TYPE_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_PROVISIONING_TASK_EXECUTOR_USER_DIMENSION';
desc ANALYTICS_PROVISIONING_TASK_EXECUTOR_USER_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_PROVISIONING_TASK_FACT';
desc ANALYTICS_PROVISIONING_TASK_FACT ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_PROVISIONING_TASK_QUEUE_ENTRY_DIMENSION';
desc ANALYTICS_PROVISIONING_TASK_QUEUE_ENTRY_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_PROVISIONING_TASK_QUEUE_FACT';
desc ANALYTICS_PROVISIONING_TASK_QUEUE_FACT ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_PROVISIONING_TASK_QUEUE_NAME_DIMENSION';
desc ANALYTICS_PROVISIONING_TASK_QUEUE_NAME_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_PROVISIONING_TASK_QUEUE_TYPE_DIMENSION';
desc ANALYTICS_PROVISIONING_TASK_QUEUE_TYPE_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_PROVISIONING_TASK_TYPE_DIMENSION';
desc ANALYTICS_PROVISIONING_TASK_TYPE_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_RECONCILIATION_RESUME_BATCH_DIMENSION';
desc ANALYTICS_RECONCILIATION_RESUME_BATCH_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_RECONCILIATION_RESUME_FACT';
desc ANALYTICS_RECONCILIATION_RESUME_FACT ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_RECONCILIATION_RESUME_PROFILE_DIMENSION';
desc ANALYTICS_RECONCILIATION_RESUME_PROFILE_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_RECONCILIATION_RESUME_RESOURCE_DIMENSION';
desc ANALYTICS_RECONCILIATION_RESUME_RESOURCE_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_RECONCILIATION_SITUATION_BATCH_DIMENSION';
desc ANALYTICS_RECONCILIATION_SITUATION_BATCH_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_RECONCILIATION_SITUATION_ENTRY_TYPE_DIMENSION';
desc ANALYTICS_RECONCILIATION_SITUATION_ENTRY_TYPE_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_RECONCILIATION_SITUATION_FACT';
desc ANALYTICS_RECONCILIATION_SITUATION_FACT ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_RECONCILIATION_SITUATION_PROFILE_DIMENSION';
desc ANALYTICS_RECONCILIATION_SITUATION_PROFILE_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_RECONCILIATION_SITUATION_RESOURCE_DIMENSION';
desc ANALYTICS_RECONCILIATION_SITUATION_RESOURCE_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_REQUEST_APPROVAL_TASK_ENTRY_DIMENSION';
desc ANALYTICS_REQUEST_APPROVAL_TASK_ENTRY_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_REQUEST_APPROVAL_TASK_EXECUTOR_ENTRY_DIMENSION';
desc ANALYTICS_REQUEST_APPROVAL_TASK_EXECUTOR_ENTRY_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_REQUEST_APPROVAL_TASK_EXECUTOR_FACT';
desc ANALYTICS_REQUEST_APPROVAL_TASK_EXECUTOR_FACT ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_REQUEST_APPROVAL_TASK_EXECUTOR_TYPE_DIMENSION';
desc ANALYTICS_REQUEST_APPROVAL_TASK_EXECUTOR_TYPE_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_REQUEST_APPROVAL_TASK_EXECUTOR_USER_DIMENSION';
desc ANALYTICS_REQUEST_APPROVAL_TASK_EXECUTOR_USER_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_REQUEST_APPROVAL_TASK_FACT';
desc ANALYTICS_REQUEST_APPROVAL_TASK_FACT ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_REQUEST_APPROVAL_TASK_TYPE_DIMENSION';
desc ANALYTICS_REQUEST_APPROVAL_TASK_TYPE_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_REQUEST_RESUME_ENTRYTYPE_DIMENSION';
desc ANALYTICS_REQUEST_RESUME_ENTRYTYPE_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_REQUEST_RESUME_FACT';
desc ANALYTICS_REQUEST_RESUME_FACT ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ANALYTICS_REQUEST_RESUME_TYPE_DIMENSION';
desc ANALYTICS_REQUEST_RESUME_TYPE_DIMENSION ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'Account';
desc Account ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'AccountNotificationSettings';
desc AccountNotificationSettings ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'AccountPasswordVault';
desc AccountPasswordVault ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ApprovalPolicy';
desc ApprovalPolicy ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ApprovalTaskDetail';
desc ApprovalTaskDetail ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'AssignmentDirectoryEntry';
desc AssignmentDirectoryEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'AssignmentEntry';
desc AssignmentEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'AssignmentPolicy';
desc AssignmentPolicy ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'AssignmentRoleRevokeEntry';
desc AssignmentRoleRevokeEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'AssignmentRoleRevokeRole';
desc AssignmentRoleRevokeRole ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'AssignmentRoleRevokeUser';
desc AssignmentRoleRevokeUser ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'AssociationRule';
desc AssociationRule ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'AttributeMap';
desc AttributeMap ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'AttributeMapping';
desc AttributeMapping ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'AttributeMapping_AttributeMap';
desc AttributeMapping_AttributeMap ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'AuthenticationMethodsNotificationSettings';
desc AuthenticationMethodsNotificationSettings ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'AuthenticationPolicy';
desc AuthenticationPolicy ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'AuthenticationPolicyParameters';
desc AuthenticationPolicyParameters ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'AuthenticationSourceKerberos';
desc AuthenticationSourceKerberos ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'AuthenticationSourceLDAP';
desc AuthenticationSourceLDAP ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'AuthenticationSourceOpenId';
desc AuthenticationSourceOpenId ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'AuthenticationSourceSaml';
desc AuthenticationSourceSaml ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'BlazonAccessManagerSession';
desc BlazonAccessManagerSession ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'BlazonAccessManagerSessionAttributes';
desc BlazonAccessManagerSessionAttributes ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'BlazonRequest';
desc BlazonRequest ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'BlazonRequestApprovalTask';
desc BlazonRequestApprovalTask ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'BlazonRequestDirectoryEntry';
desc BlazonRequestDirectoryEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'BlazonRequestNotificationSettings';
desc BlazonRequestNotificationSettings ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'BlazonRequestSodApprovalTask';
desc BlazonRequestSodApprovalTask ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'BlazonRequestTransitionState';
desc BlazonRequestTransitionState ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'BlazonRequest_dependsOnIds';
desc BlazonRequest_dependsOnIds ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'BllazonImage';
desc BllazonImage ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'CampaignDefinition';
desc CampaignDefinition ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'CampaignDefinition_CertificationPolicy';
desc CampaignDefinition_CertificationPolicy ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'CampaignExecutionInstance';
desc CampaignExecutionInstance ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'CampaignExecutionInstance_CertificationEntry';
desc CampaignExecutionInstance_CertificationEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'CertificationApprovalTask';
desc CertificationApprovalTask ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'CertificationApprovalTaskDetail';
desc CertificationApprovalTaskDetail ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'CertificationDirectoryEntry';
desc CertificationDirectoryEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'CertificationEntry';
desc CertificationEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'CertificationEntryTransitionState';
desc CertificationEntryTransitionState ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'CertificationNotificationSettings';
desc CertificationNotificationSettings ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'CertificationPolicy';
desc CertificationPolicy ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'CertificationSelector';
desc CertificationSelector ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ChangeApplicationAccountOwnerAccount';
desc ChangeApplicationAccountOwnerAccount ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ChangeApplicationAccountOwnerEntry';
desc ChangeApplicationAccountOwnerEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ChangeApplicationAccountOwnerEntry_actions';
desc ChangeApplicationAccountOwnerEntry_actions ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ChangeApplicationAccountOwnerUser';
desc ChangeApplicationAccountOwnerUser ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ChangePasswordAccount';
desc ChangePasswordAccount ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ChangePasswordAccountEntry';
desc ChangePasswordAccountEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ChangePasswordResource';
desc ChangePasswordResource ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ChangePasswordUser';
desc ChangePasswordUser ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'CheckinAdminAccountPasswordVault';
desc CheckinAdminAccountPasswordVault ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'CreatedBy';
desc CreatedBy ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'Dictionary';
desc Dictionary ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'DictionaryWord';
desc DictionaryWord ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'Domain';
desc Domain ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'EmailQueueEntry';
desc EmailQueueEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'EmailQueueEntry_attachments';
desc EmailQueueEntry_attachments ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'EmailQueueEntry_cc';
desc EmailQueueEntry_cc ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'Entitlement';
desc Entitlement ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'Entitlement_User';
desc Entitlement_User ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'Entry';
desc Entry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'EntryAttribute';
desc EntryAttribute ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'EntryAttributeCategory';
desc EntryAttributeCategory ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'EntryAttributeValue';
desc EntryAttributeValue ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'EventSetting';
desc EventSetting ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ExpirationOptions';
desc ExpirationOptions ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'Groupp';
desc Groupp ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'Groupp_InternalPermissionGroup';
desc Groupp_InternalPermissionGroup ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'Groupp_User';
desc Groupp_User ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ImportBatch';
desc ImportBatch ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ImportBatchUser';
desc ImportBatchUser ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ImportEntry';
desc ImportEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'InactiveUserAccountRuleConfiguration';
desc InactiveUserAccountRuleConfiguration ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'Inbox';
desc Inbox ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'InternalPermission';
desc InternalPermission ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'InternalPermissionGroup';
desc InternalPermissionGroup ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'InternalPermissionGroup_InternalPermission';
desc InternalPermissionGroup_InternalPermission ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'Job';
desc Job ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'JobExecution';
desc JobExecution ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'JobInstance';
desc JobInstance ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'LogginModuleSettings';
desc LogginModuleSettings ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ManagedBy';
desc ManagedBy ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ManagedBy_objectIds';
desc ManagedBy_objectIds ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'MembershipEntitlement';
desc MembershipEntitlement ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'MembershipEntitlementNotificationSettings';
desc MembershipEntitlementNotificationSettings ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'MembershipRole';
desc MembershipRole ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'MembershipRoleNotificationSettings';
desc MembershipRoleNotificationSettings ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'MfaSettings';
desc MfaSettings ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'MicroCertificationExecutionInstance';
desc MicroCertificationExecutionInstance ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'MicroCertificationExecutionInstance_CertificationEntry';
desc MicroCertificationExecutionInstance_CertificationEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'NetworkConfig';
desc NetworkConfig ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'NotificationSettings';
desc NotificationSettings ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'OAuthAccessToken';
desc OAuthAccessToken ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'OAuthApiClient';
desc OAuthApiClient ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'OAuthClient';
desc OAuthClient ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'OAuthCode';
desc OAuthCode ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'OS_CURRENTSTEP';
desc OS_CURRENTSTEP ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'OS_CURRENTSTEP_PREV';
desc OS_CURRENTSTEP_PREV ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'OS_GROUP';
desc OS_GROUP ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'OS_HISTORYSTEP';
desc OS_HISTORYSTEP ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'OS_HISTORYSTEP_PREV';
desc OS_HISTORYSTEP_PREV ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'OS_MEMBERSHIP';
desc OS_MEMBERSHIP ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'OS_PROPERTYENTRY';
desc OS_PROPERTYENTRY ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'OS_USER';
desc OS_USER ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'OS_WFENTRY';
desc OS_WFENTRY ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'OS_WORKFLOWDEFS';
desc OS_WORKFLOWDEFS ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'OtpTimeBasedConfiguration';
desc OtpTimeBasedConfiguration ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'OtpTimeBasedUserKey';
desc OtpTimeBasedUserKey ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'Parameter';
desc Parameter ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'PasswordHistory';
desc PasswordHistory ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'PasswordPolicy';
desc PasswordPolicy ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'PasswordPolicySettings';
desc PasswordPolicySettings ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'PasswordVaultEntry';
desc PasswordVaultEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'PasswordVaultEntryAttribute';
desc PasswordVaultEntryAttribute ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'PasswordVaultNotificationSettings';
desc PasswordVaultNotificationSettings ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'PasswordVaultOwner';
desc PasswordVaultOwner ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'PasswordVaultShare';
desc PasswordVaultShare ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'PasswordVaultWebScript';
desc PasswordVaultWebScript ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ProfileSituation';
desc ProfileSituation ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ProvisioningDirectoryEntry';
desc ProvisioningDirectoryEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ProvisioningEntry';
desc ProvisioningEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ProvisioningEntryTransitionState';
desc ProvisioningEntryTransitionState ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ProvisioningNotificationSettings';
desc ProvisioningNotificationSettings ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ProvisioningParameters';
desc ProvisioningParameters ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ProvisioningTask';
desc ProvisioningTask ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ProvisioningTaskDetail';
desc ProvisioningTaskDetail ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'QRTZ_BLOB_TRIGGERS';
desc QRTZ_BLOB_TRIGGERS ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'QRTZ_CALENDARS';
desc QRTZ_CALENDARS ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'QRTZ_CRON_TRIGGERS';
desc QRTZ_CRON_TRIGGERS ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'QRTZ_FIRED_TRIGGERS';
desc QRTZ_FIRED_TRIGGERS ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'QRTZ_JOB_DETAILS';
desc QRTZ_JOB_DETAILS ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'QRTZ_LOCKS';
desc QRTZ_LOCKS ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'QRTZ_PAUSED_TRIGGER_GRPS';
desc QRTZ_PAUSED_TRIGGER_GRPS ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'QRTZ_SCHEDULER_STATE';
desc QRTZ_SCHEDULER_STATE ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'QRTZ_SIMPLE_TRIGGERS';
desc QRTZ_SIMPLE_TRIGGERS ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'QRTZ_SIMPROP_TRIGGERS';
desc QRTZ_SIMPROP_TRIGGERS ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'QRTZ_TRIGGERS';
desc QRTZ_TRIGGERS ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ReconciliationAction';
desc ReconciliationAction ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ReconciliationAction_entryTypes';
desc ReconciliationAction_entryTypes ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ReconciliationAction_situationNames';
desc ReconciliationAction_situationNames ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ReconciliationBatchEntry';
desc ReconciliationBatchEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ReconciliationDirectoryEntry';
desc ReconciliationDirectoryEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ReconciliationEntry';
desc ReconciliationEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ReconciliationEntryTransitionState';
desc ReconciliationEntryTransitionState ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ReconciliationEntry_matchedEntriesIds';
desc ReconciliationEntry_matchedEntriesIds ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ReconciliationEntry_matchedOwnersIds';
desc ReconciliationEntry_matchedOwnersIds ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ReconciliationNotificationSettings';
desc ReconciliationNotificationSettings ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ReconciliationProfile';
desc ReconciliationProfile ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ReconciliationProfile_AttributeMap';
desc ReconciliationProfile_AttributeMap ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'RemoveSharedAccountMembershipEntry';
desc RemoveSharedAccountMembershipEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'Resource';
desc Resource ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ResourceAdapter';
desc ResourceAdapter ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ResourceAdapter_instances';
desc ResourceAdapter_instances ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ResourceCategory';
desc ResourceCategory ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ResourceProvisioningProfile';
desc ResourceProvisioningProfile ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'Resource_User';
desc Resource_User ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'Rightt';
desc Rightt ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'Rightt_Entitlement';
desc Rightt_Entitlement ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'Role';
desc Role ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'RoleRightApprovalPolicy';
desc RoleRightApprovalPolicy ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'RoleRightApprovalTask';
desc RoleRightApprovalTask ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'RoleRightApprovalTaskDetail';
desc RoleRightApprovalTaskDetail ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'RoleRightDirectoryEntry';
desc RoleRightDirectoryEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'RoleRightEntry';
desc RoleRightEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'RoleRightEntryItem';
desc RoleRightEntryItem ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'RoleRightEntry_RoleRightEntryItem';
desc RoleRightEntry_RoleRightEntryItem ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'RoleRightRevokeDirectoryEntry';
desc RoleRightRevokeDirectoryEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'RoleRightRevokeEntry';
desc RoleRightRevokeEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'RoleRightRevokeNotificationSettings';
desc RoleRightRevokeNotificationSettings ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'Role_User';
desc Role_User ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'SAMLSession';
desc SAMLSession ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'SamlAuthenticationClient';
desc SamlAuthenticationClient ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'SamlAuthenticationClient_attributes';
desc SamlAuthenticationClient_attributes ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'SecretQuestion';
desc SecretQuestion ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'SecureChannelOtpConfiguration';
desc SecureChannelOtpConfiguration ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'SecureChannelToken';
desc SecureChannelToken ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'SelectorExecutionInstance';
desc SelectorExecutionInstance ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'SelectorExecutionInstance_CertificationEntry';
desc SelectorExecutionInstance_CertificationEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'SelfServiceCart';
desc SelfServiceCart ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'SelfServiceCartInstanceItem';
desc SelfServiceCartInstanceItem ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'SelfServiceCartItem';
desc SelfServiceCartItem ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'ServerMailSetup';
desc ServerMailSetup ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'SharedAccountAccount';
desc SharedAccountAccount ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'SharedAccountMembership';
desc SharedAccountMembership ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'SharedAccountUser';
desc SharedAccountUser ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'SituationDef';
desc SituationDef ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'SituationDef_entryTypes';
desc SituationDef_entryTypes ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'SodApprovalTask';
desc SodApprovalTask ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'SodApprovalTaskDetail';
desc SodApprovalTaskDetail ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'SodDirectoryEntry';
desc SodDirectoryEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'SodEntry';
desc SodEntry ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'SodEntryTransitionState';
desc SodEntryTransitionState ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'SodNotificationSettings';
desc SodNotificationSettings ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'SodPolicy';
desc SodPolicy ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'SodSettings';
desc SodSettings ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'SodTaskDetail';
desc SodTaskDetail ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'Task';
desc Task ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'TaskAssignHistory';
desc TaskAssignHistory ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'TaskComment';
desc TaskComment ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'TaskDefinition';
desc TaskDefinition ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'TaskEscalation';
desc TaskEscalation ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'TaskEscalationDefinition';
desc TaskEscalationDefinition ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'TaskQueue';
desc TaskQueue ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'TaskQueueAssignHistory';
desc TaskQueueAssignHistory ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'TaskQueue_Groupp';
desc TaskQueue_Groupp ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'TaskQueue_Task';
desc TaskQueue_Task ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'User';
desc User ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'UserAccessDetail';
desc UserAccessDetail ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'UserDevice';
desc UserDevice ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'UserNotificationSettings';
desc UserNotificationSettings ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'UserTask';
desc UserTask ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'UsernamePasswordCredentialsVaultItem';
desc UsernamePasswordCredentialsVaultItem ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'UsernamePolicy';
desc UsernamePolicy ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'VaultEntryPermission';
desc VaultEntryPermission ;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_name = 'WebHook';
desc WebHook ;
